### ISSUE TITLE
리액트 입문주차 개인과제 리뷰 - 김병연 튜터

### ISSUE THREAD

**Issue by ByungyeonKim** [G-NooN/todo-list#2]
# 좋았던 점 ✨

## README.md

이번에도 리드미 파일을 작성해주셨네요. 프로젝트 저장소에서 가장 먼저 보이는 부분이기 때문에 간단하게라도 작성하는 것이 좋죠. 아주 좋은 습관입니다!

## 불변성
filter()와 map() 메서드를 적절하게 잘 사용해서 불변성을 지키셨네요. 훌륭합니다!

## 디렉토리 구조
src 폴더 내에 구조적으로 디렉토리를 구성하셨네요. 프로젝트가 커질 수록, 계층적인 디렉토리 구조를 구성하는 것이 점점 더 중요해집니다.
 
## 컴포넌트 분리
UI를 적절하게 컴포넌트로 분리하셨네요. 조금 더 나아가서 리스트와 리스트 아이템을 컴포넌트로 만들어보는 건 어떨까요?

## 구조 분해 할당

https://github.com/G-NooN/todo-list/blob/8d8805d49afdffd9c778a6fa19ec97d52fd54b14/src/components/InputForm.jsx#L3

`props`를 구조 분해 할당을 통해 받고 있네요. `props.todoList`나 `props.setTodoList`와 같이 `props` 객체를 매번 참조할 필요 없이 바로 해당 속성을 사용할 수 있는 장점이 있죠! 더 간결하고 읽기 쉬운 코드가 되었네요. :)

---

# 개선할 수 있는 점 💪

## 명확한 목적의 태그와 시멘틱 태그

`header`, `main`, `article` 등 브라우저와 개발자 둘 모두에게 도움이 되는 시멘틱한 태그를 사용해보는 건 어떨까요? 그리고 할 일 목록은 `ul`, `li` 태그로 역할에 맞는 명확한 태그를 사용해보면 좋을 것 같습니다.

## props에 함수 넘기기

https://github.com/G-NooN/todo-list/blob/8d8805d49afdffd9c778a6fa19ec97d52fd54b14/src/App.jsx#L39

`InputForm` 컴포넌트에 set(설정자)함수 자체를 prop으로 넘기고 있네요. 부모 컴포넌트에서 핸들러를 만들어서 내려주는 건 어떨까요?

## 키관리

https://github.com/G-NooN/todo-list/blob/8d8805d49afdffd9c778a6fa19ec97d52fd54b14/src/components/InputForm.jsx#L7-L15

`todoList` 아이템의 id가 중복될 수 있어요. 현재 리스트 아이템의 `key` 속성을 `id`로 주고 있죠. 따라서 각 항목은 고유한 id 값을 가져야합니다. 지금처럼 새 객체를 만들 때 id를 `todoList.length + 1`로 하면 할 일 추가 및 삭제 시 id가 중복될 수 있습니다. 각 항목마다 고유한 id를 갖게 하도록 고민해보세요.

- 이러한 점이 왜 중요한지 알고 싶다면, 아래의 글이 도움이 될 거에요.
  - https://react-ko.dev/learn/rendering-lists

## 아주 조금 아쉬운 점들

- 제목과 내용의 입력 값에 대한 유효성 검사를 해보는 것은 어떨까요?(아무 것도 입력하지 않고 추가하기를 눌렀을 때)
- CSS 클래스명을 어떤 건 케밥케이스로, 어떤건 카멜케이스로 작성을 하셨네요. 혹시 이유가 있을까요? 일반적으로는 케밥케이스 또는 스네이크케이스로 작성을 합니다!
- 제목과 내용의 입력 값에 대한 유효성 검사를 해보는 것은 어떨까요?(아무 것도 입력하지 않고 추가하기를 눌렀을 때)

---

https://github.com/G-NooN/todo-list/blob/8d8805d49afdffd9c778a6fa19ec97d52fd54b14/src/App.jsx#L14

휴식이 중요하다는 것은 알지만, 개발하다보면 쉽지가 않죠..🥲 중간중간 꼭 스트레칭 하셔요. 정말 고생 많으셨습니다. 앞으로도 화이팅입니다! 👏

**Comment by G-NooN** [comment]
안녕하세요 튜터님. 먼저 피드백 감사합니다.

과제를 제출하고 이틀 간 무한 복습과 리팩토링만 수행했던 것 같습니다ㅎㅎ

한 가지 질문이 있습니다.

### props에 함수 넘기기
https://github.com/G-NooN/todo-list/blob/8d8805d49afdffd9c778a6fa19ec97d52fd54b14/src/App.jsx#L39

해당 부분을 `todoList={todoList} setTodoList={setTodoList}` 부분을 별도의 핸들러로 생성하여, `{propsHandler}`와 같은 형태로 자식 컴포넌트에 전달하라는 것으로 이해를 했습니다.

수강했던 강의를 바탕으로 코드를 구현했다보니, 단순하게 자식 컴포넌트에 전달할 파라미터를 부모 컴포넌트에 
`parameter={valuable}` 형태로 작성해야 한다는 것만 알고 있었는데, 해당 부분을 별도로 생성하여 적용할 수 있다는 부분이 새롭고 흥미롭게 다가왔습니다.

하지만 여기서, `{propsHandler}`를 어떤 형태로 생성해야 하는 건지 감이 잡히지 않습니다.

```javascript
const propsHandler = {};  // 객체 형태인건지...?
const propsHandler = () => {};  // 함수 형태인건지...?
```

방법을 알려주실 수 있을까요...?
